# Generated by Django 5.2.3 on 2025-08-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=15)),
            ],
        ),
    ]
